apiVersion: v1
kind: ConfigMap
metadata:
  name: api-service-config
  namespace: cinema-app
data:
  SERVER_PORT: "8082"
  DATA_SERVICE_BASE_URL: http://data-app:8081/data
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_TOPIC_REVIEW: review-topic
  KAFKA_TOPIC_MOVIE: movie-topic
  KAFKA_TOPIC_FILMCRITIC: filmcritic-topic