apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-app
  namespace: cinema-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-app
  template:
    metadata:
      labels:
        app: data-app
    spec:
      containers:
      - name: data-app
        image: serv/data_service
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: data-service-config
        - secretRef:
            name: db-secret
        ports:
        - containerPort: 8081