apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: cinema-app
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=           # base64: postgres
  DB_PWD: cG9zdGdyZXM=            # base64: postgres
  DB_NAME: Y2luZW1h                # base64: cinema
